platform :ios, '9.0'
use_frameworks!

target 'rfj' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'Google/Analytics'
  pod 'MagicalRecord'
  pod 'MHVideoPhotoGallery'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'SwiftLint'
  pod 'CocoaZ'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'Vertigo'
end

target 'rjb' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'MagicalRecord'
  pod 'MHVideoPhotoGallery'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
end

target 'rtn' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'MagicalRecord'
  pod 'MHVideoPhotoGallery'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
end
