platform :ios, '9.0'


target 'rfj' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'Google/Analytics'
  pod 'MagicalRecord'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftLint'
  pod 'CocoaZ'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'Vertigo'
  pod 'IDMPhotoBrowser'
  pod 'MBProgressHUD', '~> 1.0.0'
end

target 'rjb' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'MagicalRecord'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 4.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'Vertigo'
  pod 'IDMPhotoBrowser'
  pod 'MBProgressHUD', '~> 1.0.0'
end

target 'rtn' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'MagicalRecord'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 4.0'
  pod 'Google-Mobile-Ads-SDK', '~> 7.8'
  pod 'Vertigo'
  pod 'IDMPhotoBrowser'
  pod 'MBProgressHUD', '~> 1.0.0'
end
