platform :ios, '9.0'

target 'rfj' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'MagicalRecord'
  pod 'MHVideoPhotoGallery'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 3.7.3'
end

target 'rjb' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'MagicalRecord'
  pod 'MHVideoPhotoGallery'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 3.7.3'
end

target 'rtn' do
  pod 'AFNetworking'
  pod 'AFSoundManager'
  pod 'AWSCognito'
  pod 'AWSSNS'
  pod 'BDGShare'
  pod 'CJPAdController'
  pod 'DateTools'
  pod 'GoogleAnalytics'
  pod 'MagicalRecord'
  pod 'MHVideoPhotoGallery'
  pod 'MMMarkdown'
  pod 'UIColor-HexString'
  pod 'NSObject+Singleton'
  pod 'Reachability'
  pod 'SDWebImage', '~> 3.7.3'
end
